from PySide6 import QtCore, QtGui, QtWidgets
import resources_rc

class Ui_MainWindow():
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(resources_rc.qLoadStylesheet("style.css"))
        self.centralwidget.setObjectName("centralwidget")
        self.panel1 = QtWidgets.QFrame(self.centralwidget)
        self.panel1.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.panel1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel1.setObjectName("panel1")
        self.panel2 = QtWidgets.QFrame(self.panel1)
        self.panel2.setGeometry(QtCore.QRect(0, 580, 800, 21))
        self.panel2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel2.setObjectName("panel2")
        self.info = QtWidgets.QLabel(self.panel2)
        self.info.setGeometry(QtCore.QRect(0, 0, 211, 20))
        self.info.setMinimumSize(QtCore.QSize(211, 20))
        self.info.setMaximumSize(QtCore.QSize(211, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.progress = QtWidgets.QProgressBar(self.panel2)
        self.progress.setGeometry(QtCore.QRect(219, 0, 481, 20))
        self.progress.setMinimumSize(QtCore.QSize(481, 20))
        self.progress.setMaximumSize(QtCore.QSize(481, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.progress.setFont(font)
        self.progress.setProperty("value", 0)
        self.progress.setTextVisible(True)
        self.progress.setInvertedAppearance(False)
        self.progress.setObjectName("progress")
        self.status = QtWidgets.QLabel(self.panel2)
        self.status.setEnabled(True)
        self.status.setGeometry(QtCore.QRect(700, 0, 100, 20))
        self.status.setMinimumSize(QtCore.QSize(100, 20))
        self.status.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.status.setFont(font)
        self.status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status.setObjectName("status")
        self.panel3 = QtWidgets.QFrame(self.panel1)
        self.panel3.setGeometry(QtCore.QRect(0, 0, 799, 581))
        self.panel3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel3.setObjectName("panel3")
        self.panel4 = QtWidgets.QFrame(self.panel3)
        self.panel4.setGeometry(QtCore.QRect(0, 0, 200, 583))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel4.sizePolicy().hasHeightForWidth())
        self.panel4.setSizePolicy(sizePolicy)
        self.panel4.setMinimumSize(QtCore.QSize(200, 583))
        self.panel4.setMaximumSize(QtCore.QSize(200, 583))
        self.panel4.setToolTipDuration(0)
        self.panel4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel4.setObjectName("panel4")
        self.sidebarApps = QtWidgets.QPushButton(self.panel4)
        self.sidebarApps.setGeometry(QtCore.QRect(1, 1, 198, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebarApps.sizePolicy().hasHeightForWidth())
        self.sidebarApps.setSizePolicy(sizePolicy)
        self.sidebarApps.setMinimumSize(QtCore.QSize(198, 49))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.sidebarApps.setFont(font)
        self.sidebarApps.setStyleSheet("")
        self.sidebarApps.setObjectName("sidebarApps")
        self.sidebarInstalled = QtWidgets.QPushButton(self.panel4)
        self.sidebarInstalled.setGeometry(QtCore.QRect(1, 50, 198, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebarInstalled.sizePolicy().hasHeightForWidth())
        self.sidebarInstalled.setSizePolicy(sizePolicy)
        self.sidebarInstalled.setMinimumSize(QtCore.QSize(198, 49))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.sidebarInstalled.setFont(font)
        self.sidebarInstalled.setStyleSheet("")
        self.sidebarInstalled.setObjectName("sidebarInstalled")
        self.sidebarAbout = QtWidgets.QPushButton(self.panel4)
        self.sidebarAbout.setGeometry(QtCore.QRect(1, 100, 198, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebarAbout.sizePolicy().hasHeightForWidth())
        self.sidebarAbout.setSizePolicy(sizePolicy)
        self.sidebarAbout.setMinimumSize(QtCore.QSize(198, 49))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.sidebarAbout.setFont(font)
        self.sidebarAbout.setStyleSheet("")
        self.sidebarAbout.setObjectName("sidebarAbout")
        self.userAccount = QtWidgets.QPushButton(self.panel4)
        self.userAccount.setEnabled(True)
        self.userAccount.setGeometry(QtCore.QRect(0, 533, 198, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userAccount.sizePolicy().hasHeightForWidth())
        self.userAccount.setSizePolicy(sizePolicy)
        self.userAccount.setMinimumSize(QtCore.QSize(198, 49))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.userAccount.setFont(font)
        self.userAccount.setStyleSheet("")
        self.userAccount.setCheckable(False)
        self.userAccount.setChecked(False)
        self.userAccount.setObjectName("userAccount")
        self.userIcon = QtWidgets.QLabel(self.panel4)
        self.userIcon.setGeometry(QtCore.QRect(6, 465, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.userIcon.setFont(font)
        self.userIcon.setScaledContents(False)
        self.userIcon.setObjectName("userIcon")
        self.userUsername = QtWidgets.QLabel(self.panel4)
        self.userUsername.setGeometry(QtCore.QRect(75, 465, 121, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.userUsername.setFont(font)
        self.userUsername.setObjectName("userUsername")
        self.gridLayoutWidget = QtWidgets.QWidget(self.panel3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 0, 602, 585))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.panel5 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.panel5.setContentsMargins(0, 0, 0, 0)
        self.panel5.setObjectName("panel5")
        self.panel6 = QtWidgets.QScrollArea(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel6.sizePolicy().hasHeightForWidth())
        self.panel6.setSizePolicy(sizePolicy)
        self.panel6.setMinimumSize(QtCore.QSize(600, 583))
        self.panel6.setMaximumSize(QtCore.QSize(600, 583))
        self.panel6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.panel6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.panel6.setWidgetResizable(True)
        self.panel6.setObjectName("panel6")
        self.scroll = QtWidgets.QWidget()
        self.scroll.setGeometry(QtCore.QRect(0, 0, 600, 583))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll.sizePolicy().hasHeightForWidth())
        self.scroll.setSizePolicy(sizePolicy)
        self.scroll.setMinimumSize(QtCore.QSize(600, 583))
        self.scroll.setObjectName("scroll")
        self.panel7 = QtWidgets.QFrame(self.scroll)
        self.panel7.setGeometry(QtCore.QRect(0, 0, 600, 583))
        self.panel7.setMinimumSize(QtCore.QSize(0, 0))
        self.panel7.setStyleSheet("")
        self.panel7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel7.setObjectName("panel7")
        self.app = QtWidgets.QWidget(self.panel7)
        self.app.setGeometry(QtCore.QRect(0, 0, 122, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app.sizePolicy().hasHeightForWidth())
        self.app.setSizePolicy(sizePolicy)
        self.app.setStyleSheet("")
        self.app.setObjectName("app")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.app)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.appLayout = QtWidgets.QVBoxLayout()
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.appIcon = QtWidgets.QLabel(self.app)
        self.appIcon.setStyleSheet("border: none;")
        self.appIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.appIcon.setObjectName("appIcon")
        self.appLayout.addWidget(self.appIcon)
        self.appLabel = QtWidgets.QLabel(self.app)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.appLabel.setFont(font)
        self.appLabel.setStyleSheet("border: none;")
        self.appLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.appLabel.setObjectName("appLabel")
        self.appLayout.addWidget(self.appLabel)
        self.appButton = QtWidgets.QPushButton(self.app)
        self.appButton.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/install-inactive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/install-active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.appButton.setIcon(icon)
        self.appButton.setObjectName("appButton")
        self.appLayout.addWidget(self.appButton)
        self.verticalLayout_3.addLayout(self.appLayout)
        self.border1 = QtWidgets.QFrame(self.panel7)
        self.border1.setGeometry(QtCore.QRect(0, 570, 601, 16))
        self.border1.setFrameShape(QtWidgets.QFrame.HLine)
        self.border1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.border1.setObjectName("border1")
        self.panel6.setWidget(self.scroll)
        self.panel5.addWidget(self.panel6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fated"))
        self.info.setText(_translate("MainWindow", "Fated v1.0 - Project BlockBreaker"))
        self.status.setText(_translate("MainWindow", "Ready"))
        self.sidebarApps.setText(_translate("MainWindow", "Apps"))
        self.sidebarInstalled.setText(_translate("MainWindow", "Installed"))
        self.sidebarAbout.setText(_translate("MainWindow", "About"))
        self.userAccount.setText(_translate("MainWindow", "Account"))
        self.userIcon.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/icons/user-dark.png\"/></p></body></html>"))
        self.userUsername.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">TechnoDot</span></p></body></html>"))
        self.appIcon.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/appIcons/appIcons/discord.png\"/></p></body></html>"))
        self.appLabel.setText(_translate("MainWindow", "App"))
        self.appButton.setText(_translate("MainWindow", "Install"))

resources_rc.qInitResources()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    resources_rc.qCleanupResources()
    sys.exit(app.exec())
